name = "           Aditya roy"

print(len(name))
print(name.find("t"))
print (name.capitalize())
print (name.upper())
print (name.lower())
print(name.isdigit())
print(name.isalpha())
print(name.count("a"))
print(name.replace("t" ,"a"))
print(name*3)
print(name.endswith('y'))
print(name.lstrip())
print(name.rstrip())
print(name.strip())